services:
  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: naPraPatenAxeL13.
      POSTGRES_DB: foodisave
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend/app
    container_name: fastapi_backend
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend:/app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  frontend:
    build: ./frontend
    container_name: react_frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"
    env_file:
      - .env
    volumes:
      - /frontend
      - /frontend/node_modules
    command: ["npm", "run", "dev", "--", "--host"]

volumes:
  postgres_data:
